import{a as m,s as b,i as c}from"./assets/vendor-da73009b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();const e={form:document.querySelector(".js-search-form"),input:document.querySelector(".js-search-input"),gallery:document.querySelector(".js-gallery"),loadMoreBtn:document.querySelector(".js-load-more-btn"),loader:document.querySelector(".js-loader")};m.defaults.baseURL="https://pixabay.com/api";function M(r){const o=atob(r);return Uint8Array.from(o,n=>n.codePointAt(0))}const v=new TextDecoder().decode(M("NDQ3MzQwMDItYzM5MDBlYjc0MWM2MjEzYzdlYzI5NTNlMw=="));async function g({q:r,page:o=1,per_page:n}={}){return(await m.get("/",{params:{key:v,q:encodeURIComponent(r),image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:n}})).data}function f(r){return r.map(({webformatURL:o,largeImageURL:n,tags:d,likes:t,views:a,comments:l,downloads:y})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${o}" alt="${d}" width="360" height="152" />
            <ul class="description">
              <li class="description-items">
                <span class="accent">Likes </span>${t}
              </li>
              <li class="description-items">
                <span class="accent">Views </span>${a}
              </li>
              <li class="description-items">
                <span class="accent">Comments </span>${l}
              </li>
              <li class="description-items">
                <span class="accent">Downloads </span>${y}
              </li>
            </ul>
          </a>
        </li>`).join("")}function p(r){r.classList.remove("hidden")}function i(r){r.classList.add("hidden")}const h=new b(".js-gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),s={q:"",page:1,per_page:15,total_pages:0};i(e.loadMoreBtn);e.form.addEventListener("submit",B);async function B(r){if(r.preventDefault(),e.gallery.innerHTML="",s.page=1,e.loadMoreBtn.removeEventListener("click",u),i(e.loadMoreBtn),s.q=e.input.value.trim(),s.q==="")return c.error({message:"Search field can not be empty!",position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"});p(e.loader);try{const o=await g(s);o.hits.length===0?(e.input.value="",c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})):(s.total_pages=Math.ceil(o.totalHits/s.per_page),s.total_pages>1?(p(e.loadMoreBtn),e.loadMoreBtn.addEventListener("click",u)):i(e.loadMoreBtn),e.input.value="",e.gallery.innerHTML=f(o.hits),h.refresh())}catch(o){c.error({message:`Something went wrong... Error: ${o}`,position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})}finally{i(e.loader)}}async function u(){p(e.loader),s.page+=1,i(e.loadMoreBtn);try{const r=await g(s);e.gallery.insertAdjacentHTML("beforeend",f(r.hits)),h.refresh();const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch(r){c.error({message:`Something went wrong... Error: ${r}`,position:"topCenter",timeout:3e3,messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:"./error.svg",progressBarColor:"#b51b1b",maxWidth:"432px"})}finally{i(e.loader),s.page===s.total_pages?(e.loadMoreBtn.removeEventListener("click",u),i(e.loadMoreBtn),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3,maxWidth:"432px"})):p(e.loadMoreBtn)}}
//# sourceMappingURL=commonHelpers.js.map
